name : 1001 Inventions
brand : Sjoerd Valk
description : This is the description of my site
keyword : 
url : http://daigofuji.github.io/jekyll-foundation-5-starter/
email : daigo@daigofujiwara.com
twitter : DaigoFuji
github : DaigoFuji
author : Daigo Fujiwara
analytics : UA-8418273-8
year : 2015
markdown : kramdown
